import { INFO_EXTENSIONS, JS_EXTENSIONS } from '../constants.ts';
import { getMultiExtensionsFiles } from '../utils/iconConfig.ts';

interface FileIconsConfig {
  icon: string;
  fileExtensions?: Array<string>;
  fileNames?: Array<string>;
}

export const fileIcons: Array<FileIconsConfig> = [
  { icon: 'actionscript', fileExtensions: ['as'] },
  { icon: 'ai', fileExtensions: ['ai'] },
  {
    icon: 'android',
    fileNames: ['androidmanifest.xml'],
    fileExtensions: ['apk', 'smali', 'dex'],
  },
  { icon: 'angular', fileNames: ['angular.json'] },
  { icon: 'arduino', fileExtensions: ['ino'] },
  { icon: 'assembly', fileExtensions: ['a51', 'asm', 'inc', 'nasm', 's'] },
  { icon: 'astro', fileExtensions: ['astro'] },
  {
    icon: 'audio',
    fileExtensions: ['aiff', 'flac', 'm4a', 'mp3', 'wma', 'wav'],
  },
  { icon: 'autohotkey', fileExtensions: ['ahk'] },
  {
    icon: 'babel',
    fileNames: [
      ...getMultiExtensionsFiles('babel.config', [...JS_EXTENSIONS, '.json']),
      ...getMultiExtensionsFiles('.babelrc', [...JS_EXTENSIONS, '.json', '']),
    ],
  },
  {
    icon: 'biome',
    fileNames: getMultiExtensionsFiles('biome', ['.json', '.jsonc']),
  },
  {
    icon: 'blade',
    fileExtensions: getMultiExtensionsFiles('blade', ['', '.php']),
  },
  { icon: 'browserlist', fileNames: ['.browserslistrc'] },
  { icon: 'bun', fileNames: ['bunfig.toml', '.bunfig.toml'] },
  { icon: 'bun-lock', fileNames: ['bun.lock'] },
  { icon: 'cabal', fileExtensions: ['cabal'] },
  { icon: 'cargo', fileNames: ['cargo.toml'] },
  { icon: 'cargo-lock', fileNames: ['cargo.lock'] },
  { icon: 'certificate', fileExtensions: ['cer', 'cert', 'crt'] },
  {
    icon: 'changelog',
    fileNames: getMultiExtensionsFiles('changelog', INFO_EXTENSIONS),
  },
  { icon: 'cmake', fileExtensions: ['cmake'] },
  { icon: 'coffee', fileExtensions: ['coffee'] },
  {
    icon: 'conduct',
    fileNames: getMultiExtensionsFiles('code_of_conduct', INFO_EXTENSIONS),
  },
  { icon: 'console', fileExtensions: ['bash', 'fish', 'ps1', 'sh', 'zsh'] },
  {
    icon: 'contributing',
    fileNames: getMultiExtensionsFiles('contributing', INFO_EXTENSIONS),
  },
  {
    icon: 'credits',
    fileNames: getMultiExtensionsFiles('credits', INFO_EXTENSIONS),
  },
  { icon: 'crystal', fileExtensions: ['ecr', 'cr'] },
  { icon: 'css-map', fileExtensions: ['css.map'] },
  { icon: 'cuda', fileExtensions: ['cu'] },
  { icon: 'd', fileExtensions: ['d'] },
  {
    icon: 'database',
    fileExtensions: [
      'pdb',
      'sql',
      'pks',
      'pkb',
      'accdb',
      'mdb',
      'pgsql',
      'postgres',
      'plpgsql',
      'psql',
      'dat',
    ],
  },
  {
    icon: 'deno',
    fileNames: getMultiExtensionsFiles('deno', ['.json', '.jsonc']),
  },
  { icon: 'deno-lock', fileNames: ['deno.lock'] },
  {
    icon: 'docker',
    fileNames: [
      'dockerfile',
      'containerfile',
      'docker-compose.yml',
      'compose.yaml',
    ],
  },
  { icon: 'elixir', fileExtensions: ['ex', 'eex', 'exs'] },
  { icon: 'elixir-lock', fileNames: ['mix.lock'] },
  { icon: 'elm', fileExtensions: ['elm'] },
  { icon: 'erlang', fileExtensions: ['erl'] },
  {
    icon: 'eslint',
    fileNames: [
      ...getMultiExtensionsFiles('.eslintrc', [
        '.js',
        '.cjs',
        '.yaml',
        '.yml',
        '.json',
      ]),
      ...getMultiExtensionsFiles('eslint.config', JS_EXTENSIONS),
      '.eslintignore',
    ],
  },
  { icon: 'exe', fileExtensions: ['exe'] },
  { icon: 'favicon', fileNames: ['favicon.ico'] },
  {
    icon: 'firebase',
    fileNames: ['firebase.json', '.firebaserc'],
  },
  { icon: 'flow', fileNames: ['.flowconfig'] },
  {
    icon: 'font',
    fileExtensions: [
      'woff',
      'woff2',
      'ttf',
      'eot',
      'suit',
      'otf',
      'bmap',
      'fnt',
      'odttf',
      'ttc',
      'font',
      'fonts',
      'sui',
      'ntf',
      'mrf',
    ],
  },
  { icon: 'gatsby', fileNames: ['gatsby.config.js'] },
  {
    icon: 'git',
    fileNames: [
      '.gitignore',
      '.gitconfig',
      '.gitattributes',
      '.gitmodules',
      '.gitkeep',
    ],
  },
  { icon: 'gitlab', fileNames: ['.gitlab-ci.yml'] },
  { icon: 'gleam', fileExtensions: ['gleam'] },
  { icon: 'go-mod', fileNames: ['go.mod'] },
  { icon: 'go-sum', fileNames: ['go.sum'] },
  {
    icon: 'gradle',
    fileNames: [
      ...getMultiExtensionsFiles('gradlew', ['', '.bat']),
      'gradle.properties',
      'gradle-wrapper.properties',
    ],
  },
  {
    icon: 'graphql',
    fileNames: getMultiExtensionsFiles('.graphqlconfig', ['.yml', '.yaml']),
  },
  { icon: 'graphviz', fileExtensions: ['gv'] },
  { icon: 'grunt', fileNames: ['gruntfile.js'] },
  {
    icon: 'gulp',
    fileNames: getMultiExtensionsFiles('gulpfile', JS_EXTENSIONS),
  },
  { icon: 'haml', fileExtensions: ['haml'] },
  { icon: 'haskell', fileExtensions: ['hs'] },
  { icon: 'haxe', fileExtensions: ['hx'] },
  { icon: 'html', fileExtensions: ['ascx', 'asp', 'aspx', 'ejs'] },
  {
    icon: 'image',
    fileExtensions: [
      'ami',
      'apx',
      'bmp',
      'bpg',
      'brk',
      'gif',
      'ico',
      'img',
      'png',
      'raw',
      'webp',
    ],
  },
  { icon: 'ionic', fileNames: ['ionic.config.json'] },
  { icon: 'jenkins', fileNames: ['jenkinsfile'] },
  {
    icon: 'jest',
    fileNames: getMultiExtensionsFiles('jest.config', [
      ...JS_EXTENSIONS,
      '.json',
    ]),
  },
  { icon: 'js-map', fileExtensions: ['js.map', 'mjs.map', 'cjs.map'] },
  { icon: 'json', fileNames: ['composer.lock'] },
  { icon: 'jupyter', fileExtensions: ['ipynb'] },
  { icon: 'key', fileExtensions: ['asc', 'key', 'pem', 'pub'] },
  { icon: 'kivy', fileExtensions: ['kv'] },
  { icon: 'kotlin', fileExtensions: ['kt', 'kts'] },
  { icon: 'lib', fileExtensions: ['lib'] },
  {
    icon: 'license',
    fileNames: [
      ...getMultiExtensionsFiles('copying', INFO_EXTENSIONS),
      ...getMultiExtensionsFiles('copyright', INFO_EXTENSIONS),
      ...getMultiExtensionsFiles('license', INFO_EXTENSIONS),
      'license-agpl',
      'license-apache',
      'license-bsd',
      'license-mit',
      'license-gpl',
      'license-lgpl',
    ],
  },
  { icon: 'liquid', fileExtensions: ['liquid'] },
  { icon: 'markojs', fileExtensions: ['marko'] },
  { icon: 'matlab', fileExtensions: ['matlab'] },
  { icon: 'mdx', fileExtensions: ['mdx'] },
  {
    icon: 'movie',
    fileExtensions: [
      'webm',
      'mkv',
      'flv',
      'vob',
      'ogv',
      'ogg',
      'gifv',
      'avi',
      'mov',
      'qt',
      'wmv',
      'yuv',
      'rm',
      'rmvb',
      'mp4',
      'm4v',
      'mpg',
      'mp2',
      'mpeg',
      'mpe',
      'mpv',
      'm2v',
    ],
  },
  { icon: 'mustache', fileExtensions: ['mustache'] },
  {
    icon: 'nextjs',
    fileNames: getMultiExtensionsFiles('next.config', JS_EXTENSIONS),
  },
  { icon: 'nginx', fileNames: ['nginx.conf', 'upstream.conf'] },
  { icon: 'nix', fileExtensions: ['nix'] },
  { icon: 'node', fileNames: ['.nvmrc', 'node.config.json'] },
  { icon: 'note', fileExtensions: ['note'] },
  { icon: 'npm', fileNames: ['package.json', '.npmignore', '.npmrc'] },
  { icon: 'nunjucks', fileExtensions: ['njk'] },
  { icon: 'nuxt', fileNames: ['nuxt.config.js'] },
  { icon: 'ocaml', fileExtensions: ['ml', 'mli', 'mly', 'mll'] },
  { icon: 'odin', fileExtensions: ['odin'] },
  {
    icon: 'oxc',
    fileNames: [
      ...getMultiExtensionsFiles('.oxlintrc', ['.json', '.jsonc']),
      'oxlint.config.ts',
      ...getMultiExtensionsFiles('.oxfmtrc', ['.json', '.jsonc']),
      'oxfmt.config.ts',
    ],
  },
  { icon: 'package-lock', fileNames: ['package-lock.json'] },
  { icon: 'pdf', fileExtensions: ['pdf'] },
  { icon: 'pipfile-lock', fileNames: ['pipefile.lock'] },
  {
    icon: 'playwright',
    fileNames: getMultiExtensionsFiles('playwright.config', JS_EXTENSIONS),
  },
  { icon: 'pnpm', fileNames: ['pnpm-workspace.yaml', '.pnpmfile.cjs'] },
  { icon: 'pnpm-lock', fileNames: ['pnpm-lock.yaml'] },
  {
    icon: 'postcss',
    fileNames: [
      ...getMultiExtensionsFiles('.postcssrc', [
        ...JS_EXTENSIONS,
        '',
        '.json',
        '.yaml',
        '.yml',
      ]),
      ...getMultiExtensionsFiles('postcss.config', JS_EXTENSIONS),
    ],
  },
  {
    icon: 'prettier',
    fileNames: [
      ...getMultiExtensionsFiles('.prettierrc', [
        ...JS_EXTENSIONS,
        '',
        '.json',
        '.json5',
        '.yml',
        '.yaml',
        '.toml',
      ]),
      ...getMultiExtensionsFiles('prettier.config', JS_EXTENSIONS),
      '.prettierignore',
    ],
  },
  { icon: 'prisma', fileExtensions: ['prisma'] },
  { icon: 'protobuf', fileExtensions: ['proto'] },
  { icon: 'psd', fileExtensions: ['psd'] },
  { icon: 'puppet', fileExtensions: ['pp'] },
  { icon: 'python', fileNames: ['pipefile'] },
  {
    icon: 'readme',
    fileNames: getMultiExtensionsFiles('readme', INFO_EXTENSIONS),
  },
  { icon: 'reason', fileExtensions: ['re', 'rei'] },
  {
    icon: 'rolldown',
    fileNames: getMultiExtensionsFiles('rolldown.config', JS_EXTENSIONS),
  },
  {
    icon: 'rollup',
    fileNames: getMultiExtensionsFiles('rollup.config', [
      '.js',
      '.mjs',
      '.cjs',
      '.ts',
    ]),
  },
  {
    icon: 'rsbuild',
    fileNames: getMultiExtensionsFiles('rsbuild.config', JS_EXTENSIONS),
  },
  {
    icon: 'rslib',
    fileNames: getMultiExtensionsFiles('rslib.config', JS_EXTENSIONS),
  },
  {
    icon: 'rslint',
    fileNames: getMultiExtensionsFiles('rslint.config', [
      '.js',
      '.mjs',
      '.ts',
      '.mts',
    ]),
  },
  {
    icon: 'rspack',
    fileNames: getMultiExtensionsFiles('rspack.config', JS_EXTENSIONS),
  },
  {
    icon: 'rspress',
    fileNames: getMultiExtensionsFiles('rspress.config', JS_EXTENSIONS),
  },
  {
    icon: 'rstest',
    fileNames: getMultiExtensionsFiles('rstest.config', JS_EXTENSIONS),
  },
  { icon: 'http', fileExtensions: ['rest'] },
  { icon: 'scala', fileExtensions: ['scala'] },
  {
    icon: 'settings',
    fileNames: ['.editorconfig'],
    fileExtensions: [
      'dlc',
      'config',
      'conf',
      'properties',
      'prop',
      'settings',
      'option',
      'props',
      'prefs',
      'sln.dotsettings',
      'sln.dotsettings.user',
      'cfg',
      'cnf',
      'tool-versions',
      'xcconfig',
    ],
  },
  { icon: 'sketch', fileExtensions: ['sketch'] },
  { icon: 'slurm', fileExtensions: ['slurm', 'sbatch'] },
  { icon: 'sql-lite', fileExtensions: ['db', 'sqlite', 'sqlite3'] },
  {
    icon: 'storybook',
    fileExtensions: [
      ...getMultiExtensionsFiles('stories', [
        '.js',
        '.jsx',
        '.mdx',
        '.ts',
        '.tsx',
        '.svelte',
        '.vue',
      ]),
      ...getMultiExtensionsFiles('story', [
        '.js',
        '.jsx',
        '.mdx',
        '.ts',
        '.tsx',
        '.svelte',
        '.vue',
      ]),
    ],
  },
  {
    icon: 'stylelint',
    fileNames: [
      ...getMultiExtensionsFiles('stylelint.config', ['.js', '.cjs', '.mjs']),
      ...getMultiExtensionsFiles('.stylelintrc', [
        '',
        '.js',
        '.mjs',
        '.cjs',
        '.yml',
        '.yaml',
        '.json',
      ]),
      '.stylelintignore',
    ],
  },
  { icon: 'stylus', fileExtensions: ['styl'] },
  {
    icon: 'svelte',
    fileExtensions: ['svelte'],
    fileNames: getMultiExtensionsFiles('svelte.config', [
      '.js',
      '.cjs',
      '.mjs',
    ]),
  },
  { icon: 'svg', fileExtensions: ['svg'] },
  { icon: 'table', fileExtensions: ['xls', 'xlsx', 'csv'] },
  {
    icon: 'tailwind',
    fileNames: getMultiExtensionsFiles('tailwind.config', ['.js', '.ts']),
  },
  {
    icon: 'test',
    fileExtensions: getMultiExtensionsFiles('test', [
      '.jsx',
      '.js',
      '.tsx',
      '.ts',
    ]),
  },
  { icon: 'tex', fileExtensions: ['tex', 'sty', 'cls'] },
  {
    icon: 'tsdown',
    fileNames: getMultiExtensionsFiles('tsdown.config', [
      ...JS_EXTENSIONS,
      '.json',
      '',
    ]),
  },
  {
    icon: 'tune',
    fileNames: getMultiExtensionsFiles('.env', [
      '',
      '.development',
      '.testing',
      '.staging',
      '.production',
      '.local',
      '.example',
    ]),
  },
  { icon: 'typescript-def', fileExtensions: ['d.ts', 'd.mts', 'd.cts'] },
  {
    icon: 'vite',
    fileNames: getMultiExtensionsFiles('vite.config', JS_EXTENSIONS),
  },
  {
    icon: 'vitest',
    fileNames: getMultiExtensionsFiles('vitest.config', JS_EXTENSIONS),
  },
  { icon: 'vlang', fileExtensions: ['v', 'vsh'] },
  { icon: 'vscode', fileNames: ['.vscodeignore'] },
  { icon: 'vue', fileNames: ['vue.config.js'] },
  {
    icon: 'webpack',
    fileNames: getMultiExtensionsFiles('webpack.config', [
      '.js',
      '.mjs',
      '.cjs',
      '.ts',
    ]),
  },
  { icon: 'word', fileExtensions: ['doc', 'docx', 'rtf', 'odt'] },
  { icon: 'xaml', fileExtensions: ['xaml'] },
  { icon: 'xml', fileNames: ['.htaccess'] },
  { icon: 'yarn', fileNames: getMultiExtensionsFiles('.yarnrc', ['', '.yml']) },
  { icon: 'yarn-lock', fileNames: ['yarn.lock'] },
  { icon: 'zig', fileExtensions: ['zig', 'zon'] },
  {
    icon: 'zip',
    fileExtensions: [
      '7z',
      'br',
      'brotli',
      'bz2',
      'bzip2',
      'gz',
      'gzip',
      'lrz',
      'lz',
      'lz4',
      'lzma',
      'rar',
      'tar',
      'tgz',
      'txz',
      'tz',
      'xz',
      'zip',
      'zst',
    ],
  },
];
