interface FileIconsConfig {
  icon: string;
  fileExtensions?: Array<string>;
  fileNames?: Array<string>;
}

export const fileIcons: Array<FileIconsConfig> = [
  { icon: 'actionscript', fileExtensions: ['as'] },
  { icon: 'ai', fileExtensions: ['ai'] },
  {
    icon: 'android',
    fileNames: ['androidmanifest.xml'],
    fileExtensions: ['apk', 'smali', 'dex'],
  },
  { icon: 'angular', fileNames: ['angular.json', 'module.ts', 'ng-template'] },
  { icon: 'angular-component', fileExtensions: ['component.ts'] },
  { icon: 'angular-directive', fileExtensions: ['directive.ts'] },
  { icon: 'angular-guard', fileExtensions: ['guard.ts'] },
  { icon: 'angular-pipe', fileExtensions: ['pipe.ts'] },
  { icon: 'angular-resolver', fileExtensions: ['resolver.ts'] },
  { icon: 'angular-routing', fileExtensions: ['routing.ts'] },
  { icon: 'angular-service', fileExtensions: ['service.ts'] },
  { icon: 'arduino', fileExtensions: ['ino'] },
  { icon: 'assembly', fileExtensions: ['a51', 'asm', 'inc', 'nasm', 's'] },
  { icon: 'astro', fileExtensions: ['astro'] },
  {
    icon: 'audio',
    fileExtensions: ['aiff', 'flac', 'm4a', 'mp3', 'wma', 'wav'],
  },
  { icon: 'autohotkey', fileExtensions: ['ahk'] },
  {
    icon: 'babel',
    fileNames: [
      'babel.config.json',
      'babel.config.js',
      'babel.config.cjs',
      'babel.config.mjs',
      'babel.config.cts',
      'babel.config.mts',
      '.babelrc.json',
      '.babelrc.js',
      '.babelrc.cjs',
      '.babelrc.mjs',
      '.babelrc.cts',
      '.babelrc.mts',
      '.babelrc',
    ],
  },
  { icon: 'biome', fileNames: ['biome.json', 'biome.jsonc'] },
  { icon: 'blade', fileExtensions: ['blade', 'blade.php'] },
  { icon: 'browserlist', fileNames: ['.browserslistrc'] },
  { icon: 'bun', fileNames: ['bunfig.toml', '.bunfig.toml'] },
  { icon: 'bun-lock', fileNames: ['bun.lock'] },
  { icon: 'cabal', fileExtensions: ['cabal'] },
  { icon: 'cargo', fileNames: ['cargo.lock'] },
  { icon: 'certificate', fileExtensions: ['cer', 'cert', 'crt'] },
  {
    icon: 'changelog',
    fileNames: ['changelog', 'changelog.txt', 'changelog.md'],
  },
  { icon: 'cmake', fileExtensions: ['cmake'] },
  { icon: 'coffee', fileExtensions: ['coffee'] },
  {
    icon: 'conduct',
    fileNames: ['code_of_conduct', 'code_of_conduct.txt', 'code_of_conduct.md'],
  },
  { icon: 'console', fileExtensions: ['bash', 'fish', 'ps1', 'sh', 'zsh'] },
  {
    icon: 'contributing',
    fileNames: ['contributing', 'contributing.txt', 'contributing.md'],
  },
  { icon: 'credits', fileNames: ['credits', 'credits.txt', 'credits.md'] },
  { icon: 'crystal', fileExtensions: ['ecr', 'cr'] },
  { icon: 'css-map', fileExtensions: ['css.map'] },
  { icon: 'cuda', fileExtensions: ['cu'] },
  { icon: 'd', fileExtensions: ['d'] },
  {
    icon: 'database',
    fileExtensions: [
      'pdb',
      'sql',
      'pks',
      'pkb',
      'accdb',
      'mdb',
      'pgsql',
      'postgres',
      'plpgsql',
      'psql',
      'dat',
    ],
  },
  {
    icon: 'docker',
    fileNames: [
      'dockerfile',
      'containerfile',
      'docker-compose.yml',
      'compose.yaml',
    ],
  },
  { icon: 'elixir', fileExtensions: ['ex', 'eex', 'exs'] },
  { icon: 'elixir-lock', fileNames: ['mix.lock'] },
  { icon: 'elm', fileExtensions: ['elm'] },
  { icon: 'erlang', fileExtensions: ['erl'] },
  {
    icon: 'eslint',
    fileNames: [
      '.eslintignore',
      '.eslintrc.js',
      '.eslintrc.cjs',
      '.eslintrc.yaml',
      '.eslintrc.yml',
      '.eslintrc.json',
      'eslint.config.js',
      'eslint.config.mjs',
      'eslint.config.cjs',
      'eslint.config.ts',
      'eslint.config.mts',
      'eslint.config.cts',
    ],
  },
  { icon: 'exe', fileExtensions: ['exe'] },
  { icon: 'favicon', fileNames: ['favicon.ico'] },
  {
    icon: 'firebase',
    fileNames: ['firebase.json', '.firebaserc'],
    fileExtensions: ['firebase.json', '.firebaserc'],
  },
  { icon: 'flow', fileNames: ['.flowconfig'] },
  {
    icon: 'font',
    fileExtensions: [
      'woff',
      'woff2',
      'ttf',
      'eot',
      'suit',
      'otf',
      'bmap',
      'fnt',
      'odttf',
      'ttc',
      'font',
      'fonts',
      'sui',
      'ntf',
      'mrf',
    ],
  },
  { icon: 'gatsby', fileNames: ['gatsby.config.js'] },
  {
    icon: 'git',
    fileNames: [
      '.gitignore',
      '.gitconfig',
      '.gitattributes',
      '.gitmodules',
      '.gitkeep',
    ],
  },
  { icon: 'gitlab', fileNames: ['.gitlab-ci.yml'] },
  { icon: 'go-mod', fileNames: ['go.mod'] },
  { icon: 'go-sum', fileNames: ['go.sum'] },
  {
    icon: 'gradle',
    fileNames: [
      'gradlew',
      'gradlew.bat',
      'gradle.properties',
      'gradle-wrapper.properties',
    ],
  },
  { icon: 'graphql', fileNames: ['.graphqlconfig.yml', '.graphqlconfig.yaml'] },
  { icon: 'graphviz', fileExtensions: ['gv'] },
  { icon: 'grunt', fileNames: ['gruntfile.js'] },
  {
    icon: 'gulp',
    fileNames: ['gulpfile.js', 'gulpfile.mjs', 'gulpfile.cjs', 'gulpfile.ts'],
  },
  { icon: 'haml', fileExtensions: ['haml'] },
  { icon: 'haskell', fileExtensions: ['hs'] },
  { icon: 'haxe', fileExtensions: ['hx'] },
  { icon: 'html', fileExtensions: ['ascx', 'asp', 'aspx', 'ejs'] },
  {
    icon: 'image',
    fileExtensions: [
      'ami',
      'apx',
      'bmp',
      'bpg',
      'brk',
      'gif',
      'ico',
      'img',
      'png',
      'raw',
      'webp',
    ],
  },
  { icon: 'ionic', fileNames: ['ionic.config.json'] },
  { icon: 'jenkins', fileNames: ['jenkinsfile'] },
  {
    icon: 'jest',
    fileNames: [
      'jest.config.js',
      'jest.config.ts',
      'jest.config.mjs',
      'jest.config.cjs',
      'jest.config.json',
    ],
  },
  { icon: 'js-map', fileExtensions: ['js.map', 'mjs.map', 'cjs.map'] },
  { icon: 'json', fileNames: ['composer.lock'] },
  { icon: 'jupyter', fileExtensions: ['ipynb'] },
  { icon: 'key', fileExtensions: ['asc', 'key', 'pem', 'pub'] },
  { icon: 'kivy', fileExtensions: ['kv'] },
  { icon: 'kotlin', fileExtensions: ['kt', 'kts'] },
  { icon: 'lib', fileExtensions: ['lib'] },
  {
    icon: 'license',
    fileNames: [
      'copying',
      'copying.md',
      'copying.rst',
      'copying.txt',
      'copyright',
      'copyright.md',
      'copyright.rst',
      'copyright.txt',
      'license',
      'license-agpl',
      'license-apache',
      'license-bsd',
      'license-mit',
      'license-gpl',
      'license-lgpl',
      'license.md',
      'license.rst',
      'license.txt',
    ],
  },
  { icon: 'liquid', fileExtensions: ['liquid'] },
  { icon: 'markojs', fileExtensions: ['marko'] },
  { icon: 'matlab', fileExtensions: ['matlab'] },
  { icon: 'mdx', fileExtensions: ['mdx'] },
  {
    icon: 'movie',
    fileExtensions: [
      'webm',
      'mkv',
      'flv',
      'vob',
      'ogv',
      'ogg',
      'gifv',
      'avi',
      'mov',
      'qt',
      'wmv',
      'yuv',
      'rm',
      'rmvb',
      'mp4',
      'm4v',
      'mpg',
      'mp2',
      'mpeg',
      'mpe',
      'mpv',
      'm2v',
    ],
  },
  { icon: 'mustache', fileExtensions: ['mustache'] },
  {
    icon: 'nextjs',
    fileNames: ['next.config.js', 'next.config.cjs', 'next.config.mjs'],
  },
  { icon: 'nginx', fileNames: ['nginx.conf', 'upstream.conf'] },
  { icon: 'nix', fileExtensions: ['nix'] },
  { icon: 'node', fileNames: ['.nvmrc', 'node.config.json'] },
  { icon: 'note', fileExtensions: ['note'] },
  { icon: 'npm', fileNames: ['package.json', '.npmignore', '.npmrc'] },
  { icon: 'nunjucks', fileExtensions: ['njk'] },
  { icon: 'nuxt', fileNames: ['nuxt.config.js'] },
  { icon: 'ocaml', fileExtensions: ['ml', 'mli', 'mly', 'mll'] },
  { icon: 'odin', fileExtensions: ['odin'] },
  { icon: 'package-lock', fileNames: ['package-lock.json'] },
  { icon: 'pdf', fileExtensions: ['pdf'] },
  { icon: 'pipfile-lock', fileNames: ['pipefile.lock'] },
  {
    icon: 'playwright',
    fileNames: [
      'playwright.config.ts',
      'playwright.config.js',
      'playwright.config.mts',
      'playwright.config.mjs',
      'playwright.config.cts',
      'playwright.config.cjs',
    ],
  },
  {
    icon: 'postcss',
    fileNames: [
      '.postcssrc',
      '.postcssrc.json',
      '.postcssrc.yaml',
      '.postcssrc.yml',
      '.postcssrc.ts',
      '.postcssrc.cts',
      '.postcssrc.mts',
      '.postcssrc.js',
      '.postcssrc.cjs',
      '.postcssrc.mjs',
      'postcss.config.ts',
      'postcss.config.cts',
      'postcss.config.mts',
      'postcss.config.js',
      'postcss.config.cjs',
      'postcss.config.mjs',
    ],
  },
  {
    icon: 'prettier',
    fileNames: [
      '.prettierrc',
      '.prettierrc.json',
      '.prettierrc.yml',
      '.prettierrc.yaml',
      '.prettierrc.json5',
      '.prettierrc.js',
      'prettier.config.js',
      '.prettierrc.ts',
      'prettier.config.ts',
      '.prettierrc.mjs',
      'prettier.config.mjs',
      '.prettierrc.mts',
      'prettier.config.mts',
      '.prettierrc.cjs',
      'prettier.config.cjs',
      '.prettierrc.cts',
      'prettier.config.cts',
      '.prettierrc.toml',
      '.prettierignore',
    ],
  },
  { icon: 'prisma', fileExtensions: ['prisma'] },
  { icon: 'protobuf', fileExtensions: ['proto'] },
  { icon: 'psd', fileExtensions: ['psd'] },
  { icon: 'puppet', fileExtensions: ['pp'] },
  { icon: 'python', fileNames: ['pipefile'] },
  { icon: 'readme', fileNames: ['readme', 'readme.txt', 'readme.md'] },
  { icon: 'reason', fileExtensions: ['re', 'rei'] },
  {
    icon: 'rollup',
    fileNames: [
      'rollup.config.mjs',
      'rollup.config.cjs',
      'rollup.config.js',
      'rollup.config.ts',
    ],
  },
  { icon: 'http', fileExtensions: ['rest'] },
  { icon: 'scala', fileExtensions: ['scala'] },
  {
    icon: 'settings',
    fileNames: ['.editorconfig'],
    fileExtensions: [
      'dlc',
      'config',
      'conf',
      'properties',
      'prop',
      'settings',
      'option',
      'props',
      'prefs',
      'sln.dotsettings',
      'sln.dotsettings.user',
      'cfg',
      'cnf',
      'tool-versions',
      'xcconfig',
    ],
  },
  { icon: 'sketch', fileExtensions: ['sketch'] },
  { icon: 'slurm', fileExtensions: ['slurm', 'sbatch'] },
  { icon: 'sql-lite', fileExtensions: ['db', 'sqlite', 'sqlite3'] },
  {
    icon: 'storybook',
    fileExtensions: [
      'stories.js',
      'stories.jsx',
      'stories.mdx',
      'story.js',
      'story.jsx',
      'stories.ts',
      'stories.tsx',
      'story.ts',
      'story.tsx',
      'story.mdx',
      'story.svelte',
      'stories.svelte',
      'story.vue',
      'stories.vue',
    ],
  },
  {
    icon: 'stylelint',
    fileNames: [
      '.stylelintignore',
      'stylelint.config.js',
      '.stylelintrc.js',
      '.stylelintrc.mjs',
      '.stylelintrc.cjs',
      '.stylelintrc',
      '.stylelintrc.yml',
      '.stylelintrc.yaml',
      '.stylelintrc.json',
    ],
  },
  { icon: 'stylus', fileExtensions: ['styl'] },
  {
    icon: 'svelte',
    fileExtensions: ['svelte'],
    fileNames: ['svelte.config.js', 'svelte.config.cjs', 'svelte.config.mjs'],
  },
  { icon: 'svg', fileExtensions: ['svg'] },
  { icon: 'table', fileExtensions: ['xls', 'xlsx', 'csv'] },
  { icon: 'tailwind', fileNames: ['tailwind.config.js', 'tailwind.config.ts'] },
  {
    icon: 'test',
    fileExtensions: ['test.jsx', 'test.js', 'test.tsx', 'test.ts'],
  },
  { icon: 'tex', fileExtensions: ['tex', 'sty', 'cls'] },
  {
    icon: 'tune',
    fileNames: [
      '.env',
      '.env.development',
      '.env.testing',
      '.env.staging',
      '.env.production',
      '.env.local',
      '.env.example',
    ],
  },
  { icon: 'typescript-def', fileExtensions: ['d.ts', 'd.mts', 'd.cts'] },
  {
    icon: 'vite',
    fileNames: [
      'vite.config.js',
      'vite.config.mjs',
      'vite.config.cjs',
      'vite.config.ts',
      'vite.config.mts',
      'vite.config.cts',
    ],
  },
  {
    icon: 'vitest',
    fileNames: [
      'vitest.config.js',
      'vitest.config.mjs',
      'vitest.config.cjs',
      'vitest.config.ts',
      'vitest.config.mts',
      'vitest.config.cts',
    ],
  },
  { icon: 'vlang', fileExtensions: ['v', 'vsh'] },
  { icon: 'vscode', fileNames: ['.vscodeignore'] },
  { icon: 'vue', fileNames: ['vue.config.js'] },
  {
    icon: 'webpack',
    fileNames: [
      'webpack.config.js',
      'webpack.config.mjs',
      'webpack.config.cjs',
      'webpack.config.ts',
    ],
  },
  { icon: 'word', fileExtensions: ['doc', 'docx', 'rtf', 'odt'] },
  { icon: 'xaml', fileExtensions: ['xaml'] },
  { icon: 'xml', fileNames: ['.htaccess'] },
  { icon: 'yarn', fileNames: ['.yarnrc', '.yarnrc.yml'] },
  { icon: 'yarn-lock', fileNames: ['yarn.lock'] },
  { icon: 'zig', fileExtensions: ['zig', 'zon'] },
  {
    icon: 'zip',
    fileExtensions: [
      '7z',
      'br',
      'brotli',
      'bz2',
      'bzip2',
      'gz',
      'gzip',
      'lrz',
      'lz',
      'lz4',
      'lzma',
      'rar',
      'tar',
      'tgz',
      'txz',
      'tz',
      'xz',
      'zip',
      'zst',
    ],
  },
];
