interface LanguageIconsConfig {
  icon: string;
  ids: Array<string>;
}

export const languageIcons: Array<LanguageIconsConfig> = [
  { icon: 'c', ids: ['c', 'objective-c'] },
  { icon: 'clojure', ids: ['clojure'] },
  { icon: 'cmd', ids: ['bat'] },
  { icon: 'coffee', ids: ['coffeescript'] },
  { icon: 'console', ids: ['powershell', 'shellscript'] },
  { icon: 'cpp', ids: ['cpp', 'objective-cpp'] },
  { icon: 'csharp', ids: ['csharp'] },
  { icon: 'css', ids: ['css'] },
  { icon: 'cuda', ids: ['cuda-cpp'] },
  { icon: 'd', ids: ['d'] },
  { icon: 'dart', ids: ['dart'] },
  { icon: 'database', ids: ['sql'] },
  { icon: 'docker', ids: ['dockerfile'] },
  { icon: 'docker-compose', ids: ['dockercompose'] },
  { icon: 'document', ids: ['plaintext'] },
  { icon: 'fsharp', ids: ['fsharp'] },
  { icon: 'git', ids: ['diff', 'git-commit', 'git-rebase'] },
  { icon: 'go', ids: ['go'] },
  { icon: 'graphql', ids: ['graphql'] },
  { icon: 'groovy', ids: ['groovy'] },
  { icon: 'handlebars', ids: ['handlebars'] },
  { icon: 'html', ids: ['html'] },
  { icon: 'http', ids: ['http'] },
  { icon: 'hurl', ids: ['hurl'] },
  { icon: 'java', ids: ['java'] },
  { icon: 'js', ids: ['javascript'] },
  { icon: 'jsx', ids: ['javascriptreact'] },
  { icon: 'json', ids: ['json', 'jsonc', 'jsonl'] },
  { icon: 'julia', ids: ['julia'] },
  { icon: 'less', ids: ['less'] },
  { icon: 'lua', ids: ['lua'] },
  { icon: 'markdown', ids: ['markdown'] },
  { icon: 'ocaml', ids: ['ocaml'] },
  { icon: 'perl', ids: ['perl', 'perl6'] },
  { icon: 'php', ids: ['php'] },
  { icon: 'python', ids: ['python'] },
  { icon: 'r', ids: ['r'] },
  { icon: 'ruby', ids: ['ruby'] },
  { icon: 'rust', ids: ['rust'] },
  { icon: 'sass', ids: ['scss', 'sass'] },
  { icon: 'settings', ids: ['ini', 'makefile'] },
  { icon: 'swift', ids: ['swift'] },
  { icon: 'tex', ids: ['latex', 'tex'] },
  { icon: 'toml', ids: ['toml'] },
  { icon: 'typescript', ids: ['typescript'] },
  { icon: 'tsx', ids: ['typescriptreact'] },
  { icon: 'vue', ids: ['vue'] },
  { icon: 'xml', ids: ['xml', 'xsl'] },
  { icon: 'yaml', ids: ['yaml'] },
];
